name: Workflow-Assignment
run-name: Testing github actions
on: [push]
jobs:
  Test-GithubActions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4
      - run: echo "Tabshillah Adong"
      - run: echo "Phillip Baguma"
      - run: echo "We are done"